/**
 * LoginForm Component Tests
 *
 * Generated by React Native MCP Server using generate_component_test tool
 * This demonstrates comprehensive testing including:
 * - Rendering tests
 * - Interaction tests
 * - Validation tests
 * - Accessibility tests
 * - Edge cases
 */

import React from 'react';
import { render, fireEvent, waitFor } from '@testing-library/react-native';
import { LoginForm, LoginFormProps } from './sample-component';

describe('LoginForm Component', () => {
  // Mock callbacks
  const mockOnLoginSuccess = jest.fn();
  const mockOnLoginError = jest.fn();

  // Default props
  const defaultProps: LoginFormProps = {
    onLoginSuccess: mockOnLoginSuccess,
    onLoginError: mockOnLoginError,
  };

  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('Rendering', () => {
    it('should render correctly with default props', () => {
      const { getByText, getByTestId } = render(<LoginForm {...defaultProps} />);

      expect(getByText('Login')).toBeTruthy();
      expect(getByTestId('username-input')).toBeTruthy();
      expect(getByTestId('password-input')).toBeTruthy();
      expect(getByTestId('login-button')).toBeTruthy();
    });

    it('should render without error message initially', () => {
      const { queryByTestId } = render(<LoginForm {...defaultProps} />);

      expect(queryByTestId('error-message')).toBeNull();
    });

    it('should match snapshot', () => {
      const { toJSON } = render(<LoginForm {...defaultProps} />);

      expect(toJSON()).toMatchSnapshot();
    });
  });

  describe('User Input', () => {
    it('should update username input when text is entered', () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);
      const usernameInput = getByTestId('username-input');

      fireEvent.changeText(usernameInput, 'testuser');

      expect(usernameInput.props.value).toBe('testuser');
    });

    it('should update password input when text is entered', () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);
      const passwordInput = getByTestId('password-input');

      fireEvent.changeText(passwordInput, 'password123');

      expect(passwordInput.props.value).toBe('password123');
    });

    it('should mask password input', () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);
      const passwordInput = getByTestId('password-input');

      expect(passwordInput.props.secureTextEntry).toBe(true);
    });
  });

  describe('Validation', () => {
    it('should show error for username less than 3 characters', async () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);

      fireEvent.changeText(getByTestId('username-input'), 'ab');
      fireEvent.changeText(getByTestId('password-input'), 'password123');
      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(getByTestId('error-message')).toBeTruthy();
      });

      expect(mockOnLoginError).toHaveBeenCalledWith(
        'Username must be at least 3 characters and alphanumeric'
      );
    });

    it('should show error for invalid username characters', async () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);

      fireEvent.changeText(getByTestId('username-input'), 'test@user');
      fireEvent.changeText(getByTestId('password-input'), 'password123');
      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(getByTestId('error-message')).toBeTruthy();
      });

      expect(mockOnLoginError).toHaveBeenCalled();
    });

    it('should show error for password less than 6 characters', async () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);

      fireEvent.changeText(getByTestId('username-input'), 'testuser');
      fireEvent.changeText(getByTestId('password-input'), '12345');
      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(getByTestId('error-message')).toBeTruthy();
      });

      expect(mockOnLoginError).toHaveBeenCalledWith(
        'Password must be at least 6 characters'
      );
    });

    it('should use custom validator when provided', async () => {
      const customValidator = jest.fn(() => false);

      const { getByTestId } = render(
        <LoginForm {...defaultProps} validateUsername={customValidator} />
      );

      fireEvent.changeText(getByTestId('username-input'), 'testuser');
      fireEvent.changeText(getByTestId('password-input'), 'password123');
      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(customValidator).toHaveBeenCalledWith('testuser');
      });
    });
  });

  describe('Login Flow', () => {
    it('should call onLoginSuccess with valid credentials', async () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);

      fireEvent.changeText(getByTestId('username-input'), 'testuser');
      fireEvent.changeText(getByTestId('password-input'), 'password123');
      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(mockOnLoginSuccess).toHaveBeenCalledWith('testuser');
      });
    });

    it('should show loading indicator during login', async () => {
      const { getByTestId, queryByTestId } = render(<LoginForm {...defaultProps} />);

      fireEvent.changeText(getByTestId('username-input'), 'testuser');
      fireEvent.changeText(getByTestId('password-input'), 'password123');
      fireEvent.press(getByTestId('login-button'));

      // Should show loading indicator
      expect(queryByTestId('loading-indicator')).toBeTruthy();

      await waitFor(() => {
        // Loading indicator should be gone after completion
        expect(queryByTestId('loading-indicator')).toBeNull();
      });
    });

    it('should disable inputs during loading', () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);

      fireEvent.changeText(getByTestId('username-input'), 'testuser');
      fireEvent.changeText(getByTestId('password-input'), 'password123');
      fireEvent.press(getByTestId('login-button'));

      expect(getByTestId('username-input').props.editable).toBe(false);
      expect(getByTestId('password-input').props.editable).toBe(false);
    });

    it('should disable login button during loading', () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);

      fireEvent.changeText(getByTestId('username-input'), 'testuser');
      fireEvent.changeText(getByTestId('password-input'), 'password123');
      fireEvent.press(getByTestId('login-button'));

      expect(getByTestId('login-button').props.disabled).toBe(true);
    });

    it('should clear error when starting new login attempt', async () => {
      const { getByTestId, queryByTestId } = render(<LoginForm {...defaultProps} />);

      // Trigger validation error
      fireEvent.changeText(getByTestId('username-input'), 'ab');
      fireEvent.changeText(getByTestId('password-input'), 'password123');
      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(queryByTestId('error-message')).toBeTruthy();
      });

      // Fix input and retry
      fireEvent.changeText(getByTestId('username-input'), 'testuser');
      fireEvent.press(getByTestId('login-button'));

      // Error should be cleared
      expect(queryByTestId('error-message')).toBeNull();
    });
  });

  describe('Edge Cases', () => {
    it('should handle empty inputs', async () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);

      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(mockOnLoginError).toHaveBeenCalled();
      });

      expect(mockOnLoginSuccess).not.toHaveBeenCalled();
    });

    it('should handle whitespace-only username', async () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);

      fireEvent.changeText(getByTestId('username-input'), '   ');
      fireEvent.changeText(getByTestId('password-input'), 'password123');
      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(mockOnLoginError).toHaveBeenCalled();
      });
    });

    it('should handle very long username', async () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);
      const longUsername = 'a'.repeat(1000);

      fireEvent.changeText(getByTestId('username-input'), longUsername);
      fireEvent.changeText(getByTestId('password-input'), 'password123');
      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(mockOnLoginSuccess).toHaveBeenCalledWith(longUsername);
      });
    });

    it('should handle special characters in password', async () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);

      fireEvent.changeText(getByTestId('username-input'), 'testuser');
      fireEvent.changeText(getByTestId('password-input'), '!@#$%^&*()');
      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(mockOnLoginSuccess).toHaveBeenCalled();
      });
    });
  });

  describe('Accessibility', () => {
    it('should have accessible testIDs for automation', () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);

      expect(getByTestId('username-input')).toBeTruthy();
      expect(getByTestId('password-input')).toBeTruthy();
      expect(getByTestId('login-button')).toBeTruthy();
    });

    it('should show error message with accessible testID', async () => {
      const { getByTestId } = render(<LoginForm {...defaultProps} />);

      fireEvent.changeText(getByTestId('username-input'), 'ab');
      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(getByTestId('error-message')).toBeTruthy();
      });
    });
  });

  describe('Props', () => {
    it('should call onLoginSuccess prop when login succeeds', async () => {
      const customOnSuccess = jest.fn();

      const { getByTestId } = render(
        <LoginForm {...defaultProps} onLoginSuccess={customOnSuccess} />
      );

      fireEvent.changeText(getByTestId('username-input'), 'testuser');
      fireEvent.changeText(getByTestId('password-input'), 'password123');
      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(customOnSuccess).toHaveBeenCalledWith('testuser');
      });
    });

    it('should call onLoginError prop when validation fails', async () => {
      const customOnError = jest.fn();

      const { getByTestId } = render(
        <LoginForm {...defaultProps} onLoginError={customOnError} />
      );

      fireEvent.changeText(getByTestId('username-input'), 'ab');
      fireEvent.press(getByTestId('login-button'));

      await waitFor(() => {
        expect(customOnError).toHaveBeenCalled();
      });
    });
  });
});
